# Generated by Django 5.1.1 on 2024-09-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_male',
        ),
    ]
