# Generated by Django 5.1.1 on 2024-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customer_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
