# Generated by Django 5.1.1 on 2024-10-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
