# Generated by Django 5.1.1 on 2024-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customer_address_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='customers/'),
        ),
    ]
