# Generated by Django 5.1.1 on 2024-09-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoryparent_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
